### ISSUE TITLE
Get-ADComputer : One or more properties are invalid. Parameter name: ms-Mcs-AdmPwd

### ISSUE THREAD

**Issue by NicolasGARCIA95** [LoicVeirman/Laps#2]
Hi Loic,

Thanks for sharing this script.
I was testing it in an environment where only Modern LAPS was enabled and so I get this error: Get-ADComputer : One or more properties are invalid. Parameter name: ms-Mcs-AdmPwd

To fix it quickly, I've just modified line 16 and removed the ms-Mcs-AdmPwd properties.
$Computer = Get-ADComputer -Filter { enabled -eq $true } -Properties OperatingSystem,LastLogonTimeStamp,msLaps-EncryptedPassword

I've also added a condition to filter on OperatingSystem version because we have LDAPS deployed only on workstations.

**Comment by LoicVeirman** [comment]
Hi Nicolas,

Thanks for sharing your input. The proper solution should be to ensure the schema is extended for the legacy LAPS and adapt the ldap query in consequence.

**Comment by LoicVeirman** [comment]
code updated.
